"""initial schema

Revision ID: 195d03b4db39
Revises:
Create Date: 2026-08-25 05:36:12.948987

"""

from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "195d03b4db39"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extensions first: the vector type and gen_random_uuid() are used by
    # columns created below.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("name_hi", sa.String(length=100), nullable=True),
        sa.Column("icon", sa.String(length=16), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.create_index(
        "ix_categories_display_order", "categories", ["display_order"], unique=False
    )
    op.create_table(
        "tags",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("slug", name=op.f("uq_tags_slug")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column(
            "role",
            sa.Enum("user", "moderator", "admin", name="user_role"),
            server_default="user",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "comment_reply",
                "new_scheme",
                "deadline_reminder",
                "system",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_unread",
        "notifications",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.create_index(
        "ix_notifications_user_created",
        "notifications",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.UUID(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_id_refresh_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        "ix_refresh_tokens_active",
        "refresh_tokens",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index(
        "ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("reporter_id", sa.UUID(), nullable=True),
        sa.Column(
            "target_type",
            sa.Enum("scheme", "comment", name="report_target_type"),
            nullable=False,
        ),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "outdated", "incorrect", "spam", "abusive", "other", name="report_reason"
            ),
            nullable=False,
        ),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("open", "reviewed", "dismissed", name="report_status"),
            server_default="open",
            nullable=False,
        ),
        sa.Column("resolved_by_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
            name=op.f("fk_reports_reporter_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
            name=op.f("fk_reports_resolved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        "ix_reports_open",
        "reports",
        [sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_index(
        "ix_reports_target", "reports", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "schemes",
        sa.Column("scheme_id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("name_hi", sa.String(length=500), nullable=True),
        sa.Column("ministry", sa.String(length=300), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column(
            "scheme_type",
            sa.Enum(
                "subsidy",
                "scholarship",
                "loan",
                "pension",
                "insurance",
                "training",
                "award",
                "grant",
                "other",
                name="scheme_type",
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column(
            "jurisdiction",
            sa.Enum("central", "state", name="jurisdiction"),
            server_default="central",
            nullable=False,
        ),
        sa.Column("state_code", sa.String(length=3), nullable=True),
        sa.Column("description_short", sa.Text(), nullable=True),
        sa.Column("description_long", sa.Text(), nullable=True),
        sa.Column("official_url", sa.Text(), nullable=True),
        sa.Column("application_deadline", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=100), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("needs_review", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "raw_eligibility", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("like_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("save_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("comment_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rating_sum", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rating_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(name, '')), 'A') || setweight(to_tsvector('english', coalesce(description_long, '')), 'B') || setweight(to_tsvector('english', coalesce(ministry, '')), 'C')",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(jurisdiction = 'central') OR (jurisdiction = 'state' AND state_code IS NOT NULL)",
            name=op.f("ck_schemes_state_scheme_requires_state_code"),
        ),
        sa.CheckConstraint(
            "comment_count >= 0", name=op.f("ck_schemes_comment_count_non_negative")
        ),
        sa.CheckConstraint(
            "like_count >= 0", name=op.f("ck_schemes_like_count_non_negative")
        ),
        sa.CheckConstraint(
            "rating_count >= 0", name=op.f("ck_schemes_rating_count_non_negative")
        ),
        sa.CheckConstraint(
            "save_count >= 0", name=op.f("ck_schemes_save_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_schemes_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("scheme_id", name=op.f("pk_schemes")),
        sa.UniqueConstraint("slug", name=op.f("uq_schemes_slug")),
    )
    op.create_index(
        "ix_schemes_category_active",
        "schemes",
        ["category_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_schemes_embedding_hnsw",
        "schemes",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_schemes_jurisdiction_state",
        "schemes",
        ["jurisdiction", "state_code"],
        unique=False,
    )
    op.create_index(
        "ix_schemes_like_count",
        "schemes",
        [sa.literal_column("like_count DESC")],
        unique=False,
    )
    op.create_index(
        "ix_schemes_search_vector",
        "schemes",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("is_woman", sa.Boolean(), nullable=True),
        sa.Column("is_sc_st", sa.Boolean(), nullable=True),
        sa.Column("is_obc", sa.Boolean(), nullable=True),
        sa.Column("is_minority", sa.Boolean(), nullable=True),
        sa.Column("is_divyang", sa.Boolean(), nullable=True),
        sa.Column("annual_income", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("is_ews", sa.Boolean(), nullable=True),
        sa.Column("is_lig", sa.Boolean(), nullable=True),
        sa.Column("is_mig", sa.Boolean(), nullable=True),
        sa.Column("has_bpl_card", sa.Boolean(), nullable=True),
        sa.Column("has_yellow_ration_card", sa.Boolean(), nullable=True),
        sa.Column("has_orange_ration_card", sa.Boolean(), nullable=True),
        sa.Column("is_taxpayer", sa.Boolean(), nullable=True),
        sa.Column("is_pensioner_above_10k", sa.Boolean(), nullable=True),
        sa.Column("is_farmer", sa.Boolean(), nullable=True),
        sa.Column("owns_cultivable_land", sa.Boolean(), nullable=True),
        sa.Column("is_mgnrega_worker", sa.Boolean(), nullable=True),
        sa.Column("is_unorganized_worker", sa.Boolean(), nullable=True),
        sa.Column("has_eshram_card", sa.Boolean(), nullable=True),
        sa.Column("is_govt_employee", sa.Boolean(), nullable=True),
        sa.Column("is_student", sa.Boolean(), nullable=True),
        sa.Column("has_business_plan", sa.Boolean(), nullable=True),
        sa.Column("state_code", sa.String(length=3), nullable=True),
        sa.Column("district", sa.String(length=100), nullable=True),
        sa.Column("is_rural", sa.Boolean(), nullable=True),
        sa.Column("no_pucca_house", sa.Boolean(), nullable=True),
        sa.Column("is_pregnant_or_lactating", sa.Boolean(), nullable=True),
        sa.Column(
            "custom_attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "age IS NULL OR (age >= 0 AND age <= 120)",
            name=op.f("ck_user_profiles_age_range"),
        ),
        sa.CheckConstraint(
            "annual_income IS NULL OR annual_income >= 0",
            name=op.f("ck_user_profiles_income_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profiles")),
        sa.UniqueConstraint("user_id", name="uq_user_profiles_user_id"),
    )
    op.create_index(
        "ix_user_profiles_state_code", "user_profiles", ["state_code"], unique=False
    )
    op.create_table(
        "comments",
        sa.Column("scheme_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(content)) BETWEEN 1 AND 5000",
            name=op.f("ck_comments_content_length"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["comments.id"],
            name=op.f("fk_comments_parent_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scheme_id"],
            ["schemes.scheme_id"],
            name=op.f("fk_comments_scheme_id_schemes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_comments_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index("ix_comments_parent_id", "comments", ["parent_id"], unique=False)
    op.create_index(
        "ix_comments_scheme_created",
        "comments",
        ["scheme_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("parent_id IS NULL AND deleted_at IS NULL"),
    )
    op.create_index("ix_comments_user_id", "comments", ["user_id"], unique=False)
    op.create_table(
        "scheme_benefits",
        sa.Column("scheme_id", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=200), nullable=True),
        sa.Column("amount_text", sa.Text(), nullable=False),
        sa.Column("amount_numeric", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_truncated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["scheme_id"],
            ["schemes.scheme_id"],
            name=op.f("fk_scheme_benefits_scheme_id_schemes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheme_benefits")),
    )
    op.create_index(
        "ix_scheme_benefits_scheme_id", "scheme_benefits", ["scheme_id"], unique=False
    )
    op.create_table(
        "scheme_documents",
        sa.Column("scheme_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_mandatory", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("needs_review", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["scheme_id"],
            ["schemes.scheme_id"],
            name=op.f("fk_scheme_documents_scheme_id_schemes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheme_documents")),
    )
    op.create_index(
        "ix_scheme_documents_scheme_id", "scheme_documents", ["scheme_id"], unique=False
    )
    op.create_table(
        "scheme_eligibility_rules",
        sa.Column("scheme_id", sa.String(length=64), nullable=False),
        sa.Column("rule_group", sa.Enum("all", "any", name="rule_group"), nullable=False),
        sa.Column("attribute_key", sa.String(length=60), nullable=False),
        sa.Column(
            "operator", sa.Enum("eq", "gte", "lte", name="rule_operator"), nullable=False
        ),
        sa.Column("value_bool", sa.Boolean(), nullable=True),
        sa.Column("value_numeric", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("value_text", sa.String(length=100), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("label_hi", sa.String(length=200), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.CheckConstraint(
            "attribute_key IN ('age', 'is_woman', 'is_sc_st', 'is_obc', 'is_minority', 'is_divyang', 'annual_income', 'is_ews', 'is_lig', 'is_mig', 'has_bpl_card', 'has_yellow_ration_card', 'has_orange_ration_card', 'is_taxpayer', 'is_pensioner_above_10k', 'is_farmer', 'owns_cultivable_land', 'is_mgnrega_worker', 'is_unorganized_worker', 'has_eshram_card', 'is_govt_employee', 'is_student', 'has_business_plan', 'is_rural', 'no_pucca_house', 'state_code', 'is_pregnant_or_lactating')",
            name=op.f("ck_scheme_eligibility_rules_known_attribute_key"),
        ),
        sa.CheckConstraint(
            "num_nonnulls(value_bool, value_numeric, value_text) = 1",
            name=op.f("ck_scheme_eligibility_rules_exactly_one_value"),
        ),
        sa.ForeignKeyConstraint(
            ["scheme_id"],
            ["schemes.scheme_id"],
            name=op.f("fk_scheme_eligibility_rules_scheme_id_schemes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheme_eligibility_rules")),
        sa.UniqueConstraint(
            "scheme_id",
            "rule_group",
            "attribute_key",
            "operator",
            name="uq_scheme_eligibility_rules_scheme_group_attr_op",
        ),
    )
    op.create_index(
        "ix_scheme_eligibility_rules_attribute_key",
        "scheme_eligibility_rules",
        ["attribute_key"],
        unique=False,
    )
    op.create_index(
        "ix_scheme_eligibility_rules_scheme_group",
        "scheme_eligibility_rules",
        ["scheme_id", "rule_group"],
        unique=False,
    )
    op.create_table(
        "scheme_likes",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scheme_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scheme_id"],
            ["schemes.scheme_id"],
            name=op.f("fk_scheme_likes_scheme_id_schemes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_scheme_likes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "scheme_id", name=op.f("pk_scheme_likes")),
    )
    op.create_index(
        "ix_scheme_likes_scheme_id", "scheme_likes", ["scheme_id"], unique=False
    )
    op.create_table(
        "scheme_ratings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scheme_id", sa.String(length=64), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating BETWEEN 1 AND 5", name=op.f("ck_scheme_ratings_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["scheme_id"],
            ["schemes.scheme_id"],
            name=op.f("fk_scheme_ratings_scheme_id_schemes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_scheme_ratings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "scheme_id", name=op.f("pk_scheme_ratings")),
    )
    op.create_index(
        "ix_scheme_ratings_scheme_id", "scheme_ratings", ["scheme_id"], unique=False
    )
    op.create_table(
        "scheme_saves",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scheme_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scheme_id"],
            ["schemes.scheme_id"],
            name=op.f("fk_scheme_saves_scheme_id_schemes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_scheme_saves_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "scheme_id", name=op.f("pk_scheme_saves")),
    )
    op.create_index(
        "ix_scheme_saves_scheme_id", "scheme_saves", ["scheme_id"], unique=False
    )
    op.create_index(
        "ix_scheme_saves_user_created",
        "scheme_saves",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "scheme_tags",
        sa.Column("scheme_id", sa.String(length=64), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scheme_id"],
            ["schemes.scheme_id"],
            name=op.f("fk_scheme_tags_scheme_id_schemes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_scheme_tags_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("scheme_id", "tag_id", name=op.f("pk_scheme_tags")),
    )
    op.create_index("ix_scheme_tags_tag_id", "scheme_tags", ["tag_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scheme_tags_tag_id", table_name="scheme_tags")
    op.drop_table("scheme_tags")
    op.drop_index("ix_scheme_saves_user_created", table_name="scheme_saves")
    op.drop_index("ix_scheme_saves_scheme_id", table_name="scheme_saves")
    op.drop_table("scheme_saves")
    op.drop_index("ix_scheme_ratings_scheme_id", table_name="scheme_ratings")
    op.drop_table("scheme_ratings")
    op.drop_index("ix_scheme_likes_scheme_id", table_name="scheme_likes")
    op.drop_table("scheme_likes")
    op.drop_index(
        "ix_scheme_eligibility_rules_scheme_group", table_name="scheme_eligibility_rules"
    )
    op.drop_index(
        "ix_scheme_eligibility_rules_attribute_key", table_name="scheme_eligibility_rules"
    )
    op.drop_table("scheme_eligibility_rules")
    op.drop_index("ix_scheme_documents_scheme_id", table_name="scheme_documents")
    op.drop_table("scheme_documents")
    op.drop_index("ix_scheme_benefits_scheme_id", table_name="scheme_benefits")
    op.drop_table("scheme_benefits")
    op.drop_index("ix_comments_user_id", table_name="comments")
    op.drop_index(
        "ix_comments_scheme_created",
        table_name="comments",
        postgresql_where=sa.text("parent_id IS NULL AND deleted_at IS NULL"),
    )
    op.drop_index("ix_comments_parent_id", table_name="comments")
    op.drop_table("comments")
    op.drop_index("ix_user_profiles_state_code", table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index(
        "ix_schemes_search_vector", table_name="schemes", postgresql_using="gin"
    )
    op.drop_index("ix_schemes_like_count", table_name="schemes")
    op.drop_index("ix_schemes_jurisdiction_state", table_name="schemes")
    op.drop_index(
        "ix_schemes_embedding_hnsw",
        table_name="schemes",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_schemes_category_active", table_name="schemes")
    op.drop_table("schemes")
    op.drop_index("ix_reports_target", table_name="reports")
    op.drop_index(
        "ix_reports_open",
        table_name="reports",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_table("reports")
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_index(
        "ix_refresh_tokens_active",
        table_name="refresh_tokens",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("refresh_tokens")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_index(
        "ix_notifications_unread",
        table_name="notifications",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.drop_table("notifications")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_index("ix_users_role", table_name="users")
    op.drop_table("users")
    op.drop_table("tags")
    op.drop_index("ix_categories_display_order", table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###

    # Alembic creates enum types implicitly when creating the tables that use
    # them, but never drops them. Without this, `downgrade base` leaves the
    # types behind and the next `upgrade head` fails with
    # DuplicateObjectError. Dropped after the tables that depend on them.
    for enum_name in (
        "user_role",
        "scheme_type",
        "jurisdiction",
        "rule_group",
        "rule_operator",
        "report_target_type",
        "report_status",
        "report_reason",
        "notification_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    op.execute("DROP EXTENSION IF EXISTS vector")
    # pgcrypto is intentionally left in place: other schemas in the same
    # database may rely on it, and it is cheap to keep.
