"""import provenance

Adds import_runs, scheme_field_changes, and schemes.last_imported_at -- see
db/models/provenance.py's module docstring for what these support. No enum
types involved this time, so none of the two prior migrations' documented
autogenerate gaps (implicit enum creation on add_column, no DROP TYPE on
downgrade) apply here.

Revision ID: bfd0f4686f74
Revises: e30b191a5c64
Create Date: 2026-09-03 21:45:06.381064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfd0f4686f74'
down_revision: Union[str, Sequence[str], None] = 'e30b191a5c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_runs',
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_label', sa.String(length=200), nullable=False),
    sa.Column('source_file_hash', sa.String(length=64), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_runs'))
    )
    op.create_table('scheme_field_changes',
    sa.Column('scheme_id', sa.String(length=64), nullable=False),
    sa.Column('import_run_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('applied', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], name=op.f('fk_scheme_field_changes_import_run_id_import_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.scheme_id'], name=op.f('fk_scheme_field_changes_scheme_id_schemes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheme_field_changes'))
    )
    op.create_index('ix_scheme_field_changes_import_run_id', 'scheme_field_changes', ['import_run_id'], unique=False)
    op.create_index('ix_scheme_field_changes_scheme_applied', 'scheme_field_changes', ['scheme_id', 'applied'], unique=False)
    op.create_index('ix_scheme_field_changes_scheme_id', 'scheme_field_changes', ['scheme_id'], unique=False)
    op.add_column('schemes', sa.Column('last_imported_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemes', 'last_imported_at')
    op.drop_index('ix_scheme_field_changes_scheme_id', table_name='scheme_field_changes')
    op.drop_index('ix_scheme_field_changes_scheme_applied', table_name='scheme_field_changes')
    op.drop_index('ix_scheme_field_changes_import_run_id', table_name='scheme_field_changes')
    op.drop_table('scheme_field_changes')
    op.drop_table('import_runs')
    # ### end Alembic commands ###
