"""verification status

See ADR 0003. Every search/detail result carries this so a caller cannot
render a scheme without knowing how much it can be trusted.

Revision ID: e30b191a5c64
Revises: 4e8790001be5
Create Date: 2026-08-31 22:46:44.227433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30b191a5c64'
down_revision: Union[str, Sequence[str], None] = '4e8790001be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


verification_status_enum = sa.Enum(
    "unverified",
    "source_provided",
    "officially_verified",
    name="verification_status",
)


def upgrade() -> None:
    """Upgrade schema."""
    # A third gap alongside the two already documented in the initial
    # migration: op.add_column() with an inline sa.Enum(...) does NOT create
    # the PostgreSQL type first -- that only happens automatically for
    # create_table(), not add_column(). Without this explicit create(), the
    # ADD COLUMN below fails with UndefinedObjectError: type
    # "verification_status" does not exist.
    verification_status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schemes', sa.Column('verification_status', verification_status_enum, server_default='unverified', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemes', 'verification_status')
    # ### end Alembic commands ###

    # Same known autogenerate gap as the initial migration (see its
    # downgrade): the enum type is created implicitly and never dropped,
    # so the next `upgrade head` fails with DuplicateObjectError otherwise.
    op.execute("DROP TYPE IF EXISTS verification_status")
